version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: php_apache
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped

volumes:
  html:
